[package]
name = "cattle-common"
version.workspace = true
edition.workspace = true
license.workspace = true
authors.workspace = true

[dependencies]
serde = { workspace = true, features = ["derive", "std"] }
uuid = { workspace = true, features = ["serde", "v4"] }
